# Generated by Django 6.0.3 on 2026-04-06 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='stage',
            field=models.CharField(choices=[('idea', 'Idea/Concept'), ('planning', 'Planning/Research'), ('in_progress', 'Development/In Progress'), ('testing', 'Testing/QA'), ('Completed', 'Completed/Deployed')], default='idea', max_length=20),
        ),
    ]
