# Generated by Django 6.0.3 on 2026-04-06 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_project_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='support_required',
            field=models.CharField(default='None', max_length=400),
        ),
    ]
